name: 'Rinde de Soja en Paraguay'

forecast_date: ['2016-10-01','2016-10-15','2016-11-01','2016-11-15',
                '2016-12-01','2016-12-15','2017-01-01','2017-01-15',
                '2017-02-01','2017-02-15','2017-03-01','2017-03-15',
                '2017-04-01','2017-04-15','2017-05-01','2017-05-15']

crop_type: 'SB'
crop_template: 'SB-PY.json'

configuration:
    campaign_first_month: 9
    # Weather series type: combined, historic or artificial.
    weather_series: 'combined'

# Locations to be simulated, coordinates and OMM ID of the associated weather station
locations:
    capitan_meza: {
        name: "Capitán Meza",
        coord_x: '-55.332',
        coord_y: '-26.834',
        weather_station: 86285 }
    encarnacion: {
        name: "Encarnación",
        coord_x: '-55.896',
        coord_y: '-27.304',
        weather_station: 86297 }

# ----------------------------------------------------------------------------------------------------------------------

site_characteristics:
    capitan_meza:
        soil_1: &sc_slo_1 {
            id: "MAItapO001",                    # Soil id as it appears in the DSSAT soil file (ID_SOIL)
            series: "Itapua",                    # Soil series
            scs_family: "Kandiudalfic Eutrodox", # Taxonomic classification (USDA-Soil Taxonomy)
            prop: 0.5,                           # Proportion of area occupied by the soil in the location/cartographic unit to be simulated
            n_horizons: 5 }                      # Number of horizons of the soil
        soil_2: &sc_slo_2 {
            id: "MAItapU001",
            series: "Itapua",
            scs_family: "Rhodic Paleudult",
            prop: 0.5,
            n_horizons: 5 }
        soil_3: &sc_slo_3 {
            id: "MAItapU002",
            series: "Itapua",
            scs_family: "Typic Paleudult",
            prop: 0.5,
            n_horizons: 5 }
    encarnacion:
        soil_1: *sc_slo_1
        soil_2: *sc_slo_2
        soil_3: *sc_slo_3

# ----------------------------------------------------------------------------------------------------------------------

initial_conditions:
    capitan_meza:
        soil_1:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: &id001 [0.5, 0.5, 0.5, 0.3, 0.3]
            no3_ppm_hrzn: &id002 [8.1, 3.5, 1.3, 0.4, 0.1]
        soil_2:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: &id003 [0.5, 0.5, 0.5, 0.3, 0.3]
            no3_ppm_hrzn: &id004 [9.6, 4.3, 1.6, 0.5, 0.1]
        soil_3:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: &id005 [0.5, 0.5, 0.5, 0.3, 0.3]
            no3_ppm_hrzn: &id006 [7.1, 3.0, 1.0, 0.2, 0.1]
    encarnacion:
        soil_1:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: *id001
            no3_ppm_hrzn: *id002
        soil_2:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: *id003
            no3_ppm_hrzn: *id004
        soil_3:
            frac_soil_water_hrzn:
                high: [1.0, 1.0, 1.0, 1.0, 1.0]
                low: [0.2, 0.2, 0.2, 0.2, 0.2]
                mid: [0.5, 0.5, 0.5, 0.5, 0.5]
            nh4_ppm_hrzn: *id005
            no3_ppm_hrzn: *id006

# ----------------------------------------------------------------------------------------------------------------------

agronomic_management:

    capitan_meza:
        soil_1:
            mgmt_1: &mnjo_1 {
                mgmt_name: "990004 (4) - 20 Sep",
                cultivar_id: "990004",
                planting_date: "yyyy0920",
                irrig_date: "yyyy0921",          # Siempre un día despues de la siembra
                plant_population: 30 }
            mgmt_2: &mnjo_2 {
                mgmt_name: "990005 (5) - 20 Sep",
                cultivar_id: "990005",
                planting_date: "yyyy0920",
                irrig_date: "yyyy0921",         # Siempre un día despues de la siembra
                plant_population: 30 }
            mgmt_3: &mnjo_3 {
                mgmt_name: "990006 (6) - 20 Sep",
                cultivar_id: "990006",
                planting_date: "yyyy0920",
                irrig_date: "yyyy0921",         # Siempre un día despues de la siembra
                plant_population: 30 }
            mgmt_4: &mnjo_4 {
                mgmt_name: "DON MARIO (4) - 20 Sep",
                cultivar_id: "IB0045",
                planting_date: "yyyy0920",
                irrig_date: "yyyy0921",         # Siempre un día despues de la siembra
                plant_population: 30 }
            mgmt_5: &mnjo_5 {
                mgmt_name: "UA4L01 (4800) - 20 Sep",
                cultivar_id: "UA4L01",
                planting_date: "yyyy0920",
                irrig_date: "yyyy0921",         # Siempre un día despues de la siembra
                plant_population: 30 }
        soil_2:
            mgmt_1: *mnjo_1
            mgmt_2: *mnjo_2
            mgmt_3: *mnjo_3
            mgmt_4: *mnjo_4
            mgmt_5: *mnjo_5
        soil_3:
            mgmt_1: *mnjo_1
            mgmt_2: *mnjo_2
            mgmt_3: *mnjo_3
            mgmt_4: *mnjo_4
            mgmt_5: *mnjo_5

    encarnacion:
        soil_1:
            mgmt_1: *mnjo_1
            mgmt_2: *mnjo_2
            mgmt_3: *mnjo_3
            mgmt_4: *mnjo_4
            mgmt_5: *mnjo_5
        soil_2:
            mgmt_1: *mnjo_1
            mgmt_2: *mnjo_2
            mgmt_3: *mnjo_3
            mgmt_4: *mnjo_4
            mgmt_5: *mnjo_5
        soil_3:
            mgmt_1: *mnjo_1
            mgmt_2: *mnjo_2
            mgmt_3: *mnjo_3
            mgmt_4: *mnjo_4
            mgmt_5: *mnjo_5

# ----------------------------------------------------------------------------------------------------------------------

results:
    cycle: ["HWAM", "MDAT", "ADAT", "PDAT"]
    daily: ["WSGD", "SWTD", "SWXD", "ETAC", "EOAC"]
