__author__ = 'Federico Schmidt'

LOAD_CONFIGURATION = 110
LOAD_FORECAST = 100
CHANGE_DB_STRUCTURE = 90
UPDATE_DB_DATA = 80
UPDATE_MAX_WEATHER_DATES = 70

RUN_PSIMS = 1
RUN_FORECAST = 0
UPDATE_RAINFALL_QUANTILES = 0